force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Represents a candidate&#39;s application to a position</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApplications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <description>Related To: Candidate
Related List Label: Job Applications</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>JobApplications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public class JobApplicationTriggerHandler {

    public JobApplicationTriggerHandler(CandidateServices candidateServices){
        this.candidateServices = candidateServices;
    }

    public void afterInsert(Map<Id, Job_Application__c> newMap){
         //Send mail confirm to candidate
         for (Job_Application__c jobApplication: newMap.values()) {
                try{
                    Candidate__c candidate = candidateServices.findSendMailConfirm(jobApplication.Candidate__c);
                    if(candidate != null){
                        EmailManager.sendConfirmInterview(candidate, jobApplication);
                    }
                }catch(System.EmailException e){
                    System.debug(e);
                }
      		}  
    }
    

    private CandidateServices candidateServices;
}